# Build Instructions #
[build]
  NODE_ENV = "production"
  publish = "dist/"
  command = "npm run build:dist"

# Site Redirects #
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "https://www.dashboard.diffex.io"
  status = 200

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 200


